all: jerarquia1 jerarquia2 signals
jerarquia1:
	gcc -o jerarquia1 jerarquia1.c
jerarquia2:
	gcc -o jerarquia2 jerarquia2.c
signals:
	gcc -o signals signals.c




clean:

	rm jerarquia1 jerarquia2 signals
